name: Build SketchChair with Make

on:
  push:
    branches: [ master, develop, upgrade-merge ]
  pull_request:
    branches: [ master, develop, upgrade-merge ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 11 (Zulu)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Print build environment info
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          which javac
          javac -version
          which make
          make --version
          make info

      - name: Build with Make
        run: make compile

      - name: Test JAR creation
        run: make jar

      - name: Check build output
        run: |
          echo "Build directory contents:"
          ls -la bin/ || echo "No bin directory found"
          echo "Distribution directory contents:"
          ls -la dist/ || echo "No dist directory found"
