name: Build SketchChair Cross-Platform

on:
  push:
    branches: [ master, develop, upgrade-merge ]
  pull_request:
    branches: [ master, develop, upgrade-merge ]
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: macos
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Microsoft OpenJDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Print build environment info
        shell: bash
        run: |
          echo "Platform: ${{ matrix.platform }}"
          echo "OS: ${{ matrix.os }}"
          echo "JAVA_HOME=$JAVA_HOME"
          which javac
          javac -version
          which make || echo "Make not available, using manual build"
          make --version || echo "Make version not available"

      - name: Show build configuration
        shell: bash
        run: |
          make info || echo "Make info not available"

      - name: Build with Make
        shell: bash
        run: make compile

      - name: Create platform-specific JAR
        shell: bash
        run: |
          case "${{ matrix.platform }}" in
            "linux")
              make jar-linux
              ;;
            "windows")
              make jar-windows
              ;;
            "macos")
              make jar-macos
              ;;
          esac

      - name: Create universal executable JAR
        shell: bash
        run: make jar-with-deps

      - name: Check build outputs
        shell: bash
        run: |
          echo "Build directory contents:"
          ls -la bin/ || echo "No bin directory found"
          echo ""
          echo "Distribution directory contents:"
          find dist/ -type f -name "*.jar" 2>/dev/null || echo "No JAR files found"

      - name: Upload platform-specific artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SketchChair-${{ matrix.platform }}
          path: |
            dist/${{ matrix.platform }}/*.jar
            dist/*executable*.jar
          retention-days: 30

      - name: Upload to release (if release)
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/${{ matrix.platform }}/SketchChair-${{ matrix.platform }}-1.0.jar
          asset_name: SketchChair-${{ matrix.platform }}-1.0.jar
          asset_content_type: application/java-archive

  create-release-summary:
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Create release summary
        run: |
          echo "## SketchChair Release Build Summary" > release-summary.md
          echo "" >> release-summary.md
          echo "Built with Microsoft OpenJDK 11 for multiple platforms:" >> release-summary.md
          echo "" >> release-summary.md
          echo "### Available Downloads:" >> release-summary.md
          echo "- **macOS**: SketchChair-macos-1.0.jar" >> release-summary.md
          echo "- **Windows**: SketchChair-windows-1.0.jar" >> release-summary.md
          echo "- **Linux**: SketchChair-linux-1.0.jar" >> release-summary.md
          echo "" >> release-summary.md
          echo "### Requirements:" >> release-summary.md
          echo "- Java 11 or higher" >> release-summary.md
          echo "- Platform-specific native libraries included" >> release-summary.md
          echo "" >> release-summary.md
          echo "### Usage:" >> release-summary.md
          echo "\`\`\`bash" >> release-summary.md
          echo "java -jar SketchChair-[platform]-1.0.jar" >> release-summary.md
          echo "\`\`\`" >> release-summary.md
          
      - name: Upload release summary
        uses: actions/upload-artifact@v4
        with:
          name: release-summary
          path: release-summary.md
