name: Build with Java 1.4 using Docker
on:
  push:
    branches: [ master, develop, upgrade-merge ]
  pull_request:
    branches: [ master, develop, upgrade-merge ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: tronicum/jdk1.4:latest # <-- you must build/publish this image
    steps:
      - uses: actions/checkout@v4
      - name: Verify Java version
        run: java -version
      - name: Build
        run: javac -sourcepath src -d bin $(find src -name "*.java")
